### ISSUE TITLE
integrate new ckb + ckb-indexer

### ISSUE THREAD

**Issue by homura** [nervosnetwork/lumos#416]
## Motivation

CKB will integrate the ckb-indexer into CKB, we should make the current `@ckb-lumos/indexer` to be compatible with the new CKB node

## How

- [x] investigating the new CKB implementation
- [x] https://github.com/ckb-js/lumos/issues/436
- [x] update `@ckb-lumos/ckb-indexer` to support merged indexer
- [x] https://github.com/ckb-js/lumos/issues/429

## References

- https://github.com/nervosnetwork/ckb/pull/3598

**Comment by zhangyouxin** [comment]
## Investigation of the new CKB implementation

### Compile ckb binary

1. clone the repo: `git clone git@github.com:zhangsoledad/ckb.git`
2. checkout branch `zhangsoledad/merge-indexer`
3. follow this [link](https://docs.nervos.org/docs/basics/guides/get-ckb/) to setup env and compile ckb binary (it may take a few minutes or hours according to your network and machine performance)
5. create and cd into a blank directory then run `ckb init --c dev` to initialize a local dev chain. configure `block_assembler` in `ckb.toml`
6. start ckb node and miner:

```
ckb run
ckb miner
```

Then the console indicates that the ckb node and miner started. (restart if miner is stuck or node is stuck)

<img width="1753" alt="image" src="https://user-images.githubusercontent.com/3870972/191706521-2571a8cc-1a19-4384-a5c9-310eadf84b1b.png">

### Test indexer: `get_cells` sample：

```
// Request: 
curl --location --request POST 'http://localhost:8114' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "get_cells",
    "params": [
        {
            "script": {
                "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                "hash_type": "type",
                "args": "0xe3e0a82b199dceadb55e223c6e4b8e511d57d249"
            },
            "script_type": "lock",
            "filter": {}
        },
        "asc",
        "0x64",
        null
    ]
}'

// Response: 
{
    "jsonrpc": "2.0",
    "result": {
        "last_cursor": "0x409bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce801e3e0a82b199dceadb55e223c6e4b8e511d57d249000000000000000c0000000000000000",
        "objects": [
            {
                "block_number": "0xc",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xb0e4028536616360e428ed0ca5fc0537ba98a58868f9cd091b2e3ad7e5286793"
                },
                "output": {
                    "capacity": "0x2ecbd7f2fb",
                    "lock": {
                        "args": "0xe3e0a82b199dceadb55e223c6e4b8e511d57d249",
                        "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                        "hash_type": "type"
                    },
                    "type": null
                },
                "output_data": "0x",
                "tx_index": "0x0"
            }
        ]
    },
    "id": 0
}
```

### Test indexer: `get_transactions` sample：

```
// Request: 
curl --location --request POST 'http://localhost:8114' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "get_transactions",
    "params": [
        {
              "script": {
                "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                "hash_type": "type",
                "args": "0xe3e0a82b199dceadb55e223c6e4b8e511d57d249"
            },
            "script_type": "lock",
            "filter": {}
        },
        "asc",
        "0x64",
        null
    ]
}'

// Response: 
{
    "jsonrpc": "2.0",
    "result": {
        "last_cursor": "0x809bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce801e3e0a82b199dceadb55e223c6e4b8e511d57d249000000000000000c000000000000000001",
        "objects": [
            {
                "block_number": "0xc",
                "io_index": "0x0",
                "io_type": "output",
                "tx_hash": "0xb0e4028536616360e428ed0ca5fc0537ba98a58868f9cd091b2e3ad7e5286793",
                "tx_index": "0x0"
            }
        ]
    },
    "id": 0
}
```

### Test indexer: `get_indexer_tip` sample:

```
// Request: 
curl --location --request POST 'http://localhost:8114' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "get_indexer_tip"
}'

// Response: 
{
    "jsonrpc": "2.0",
    "result": {
        "block_hash": "0xa6acfcc22e350878c4861e21284cb125357bd1ee6d18bedcb3f6f2e2cd7db497",
        "block_number": "0xc"
    },
    "id": 2
}
```

### Conclusion

1. ckb-indexer works identical to the previous standalone ckb-indexer after merged into ckb node except for `get_tip` has been renamed to `get_indexer_tip` and removed `get_indexer_info` 
2. In order to visit new ckb-indexer, we just need to change the implementation of `indexer rpc` of `packages/ckb-indexer` by changing `get_tip` to `get_indexer_tip` in `getTip` implementation and remove `getIndexerInfo`. https://github.com/ckb-js/lumos/blob/064c601d68d6f2bca2d3796661a422dd0df9755d/packages/ckb-indexer/src/rpc.ts
